# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands:
    Unity_2021.3.6f1


steps:

# Cleanup for unity build
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**/*'

# Get the previously secured library (if any) for performance reasons
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\Library'
    Contents: '**/*'
- task: CmdLine@2
  inputs:
    script: 'if EXIST "$(Build.BinariesDirectory)\Library\" move "$(Build.BinariesDirectory)\Library" "$(Build.Repository.LocalPath)\Library"'

- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Win64'
    unityEditorsPathMode: 'specify'
    customUnityEditorsPath: 'D:\Tools\Unity\Editor'
    versionSelectionMode: 'project'
    outputPath: '$(Build.BinariesDirectory)\Build'
    outputFileName: 'UPA Build'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.BinariesDirectory)\Build'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.BinariedDirectory)\Library'
    Contents: '**/*'

- task: CmdLine@2
  inputs:
    script: 'move "$(Build.Repository.LocalPath)\Library" "$(Build.BinariesDirectory)\Library"'

# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
